name: CI_action

on:
  push:
    branches: [ main, unit-tests ]
  pull_request:
    branches: [ main, unit-tests ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SPEED

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install-react-test
      

    - name: Run the tests
      run: npm run run-react-test