# Basic CI implementation

name: CI_action

on:
  push:
    branches: [ main, production, unit-tests, backend ]
  pull_request:
    branches: [ main, production, unit-tests, backend ]

# Make sure to run on ubuntu and change working directory to ./SPEED for any runs
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SPEED

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

# React tests
# Note: The package.json in SPEED will handle moving to different directories and running frontend/backend in different places
    - name: Install react dependencies
      run: npm run install-react

    - name: Run react  tests
      run: npm run run-react-test